document.addEventListener('DOMContentLoaded', () => {
    const container = document.getElementById('portfolio-container');

    async function fetchPortfolioItems() {
        try {
            // Fetch the JSON file generated by Sveltia CMS
            const response = await fetch('./portfolio-items.json');
            
            if (!response.ok) {
                throw new Error('Could not load portfolio data.');
            }
            
            const data = await response.json();
            // Fallback to an empty array if data.items is undefined
            const items = data.items || []; 
            
            renderItems(items);
        } catch (error) {
            container.innerHTML = `<p id="status-message" style="color: red;">Error: ${error.message}</p>`;
        }
    }

    function renderItems(items) {
        // Handle empty state
        if (items.length === 0) {
            container.innerHTML = '<p id="status-message">No items found. Add some through the admin dashboard!</p>';
            return;
        }

        // Clear the "Loading..." message
        container.innerHTML = '';

        // Loop through each item in the JSON and create a card
        items.forEach(item => {
            const card = document.createElement('div');
            card.className = 'portfolio-card';

            if (item.image) {
                const image = document.createElement('img');
                const imagePath = item.image.replace(/^\/?images\//, 'images/');
                image.src = `./${imagePath}`;
                image.alt = item.title || 'Portfolio item';
                image.className = 'portfolio-image';
                card.appendChild(image);
            }

            const content = document.createElement('div');
            content.className = 'portfolio-content';

            const header = document.createElement('div');
            header.className = 'portfolio-header';

            const title = document.createElement('h2');
            title.className = 'portfolio-title';
            title.textContent = item.title || 'Untitled item';

            const titleBlock = document.createElement('div');
            const tag = document.createElement('span');
            tag.className = 'portfolio-tag';
            tag.textContent = item.category || 'Seasonal selection';
            titleBlock.append(tag, title);

            const price = document.createElement('span');
            price.className = 'portfolio-price';
            price.textContent = `₹${item.price ?? 0}`;

            header.append(titleBlock, price);

            const description = document.createElement('p');
            description.className = 'portfolio-description';
            description.textContent = item.description || '';

            content.append(header, description);
            card.appendChild(content);

            // Append the finished card to the grid
            container.appendChild(card);
        });
    }

    // Initialize the fetch process
    fetchPortfolioItems();
});